apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airflow-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  namespace: default
spec:
  rules:
  - http:
      paths:
        - path: /airflow 
          pathType: Prefix
          backend:
            service:
              name: airflow-dev-sunrise
              port: 
                number: 8080